name: Client Onboarding Automation
on:
  repository_dispatch:
    types: [form_submitted]

jobs:
  process-form:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install fpdf requests

      - name: Validate form data
        id: validation
        env:
          FORM_DATA: ${{ toJson(github.event) }}
        run: |
          echo "$FORM_DATA" | python data_validation.py > validation_result.json
          echo "validation_result=$(cat validation_result.json)" >> $GITHUB_OUTPUT

      - name: Check validation
        if: ${{ fromJson(steps.validation.outputs.validation_result).status != 'success' }}
        run: |
          echo "Validation failed: ${{ fromJson(steps.validation.outputs.validation_result).message }}"
          exit 1

      - name: Generate PDF contract
        run: |
          python pdf_generator.py "$FORM_DATA"

      - name: Update Airtable
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
        run: |
          curl -X POST "https://api.airtable.com/v0/YOUR_BASE_ID/Clients" \
          -H "Authorization: Bearer $AIRTABLE_TOKEN" \
          -H "Content-Type: application/json" \
          -d '$FORM_DATA'
