name: Client Onboarding Automation
on:
  repository_dispatch:
    types: [form_submitted]

jobs:
  process-form:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install fpdf requests

      - name: Process form data
        id: process-data
        env:
          FORM_DATA: ${{ toJson(github.event.client_payload) }}
        run: |
          # Save formatted payload for Python scripts
          echo '$FORM_DATA' > form_data.json
          cat form_data.json

          # Validate data
          python data_validation.py form_data.json
          
          # Generate PDF
          python pdf_generator.py form_data.json

      - name: Update Airtable
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        run: |
          curl -X POST "https://api.airtable.com/v0/$BASE_ID/Clients" \
          -H "Authorization: Bearer $AIRTABLE_TOKEN" \
          -H "Content-Type: application/json" \
          -d @form_data.json
